config/routes.rb
Rails.application.routes.draw do
  resources :bug_reports, except: [:edit, :update]
  resources :documents
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :tenants
  resources :foobars

  #nesting property units under
  resources :properties do
    resources :property_units do
      resources :leases, only: [:new, :show, :create, :destroy]
      resources :documents, only: [:index, :new, :show, :create, :destroy]
    end
  end
  devise_for :users, path: "user", controllers: { sessions: "users/sessions", registrations: "users/registrations"}

  devise_for :tenants, path: "tenant_space", controllers: { sessions: "tenants/sessions", confirmations: "tenants/confirmations", registrations: "tenants/registrations"}
  get 'tenant_space/index', as: 'tenant_space'
  get 'tenant_space/leases'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "properties#index"


  # Todo API namespace, makes routes render at /api/v1/todo_items
  # defaults { format: :json } ensures that the data returned from the routes is JSON.
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :todo_items, only: [:index, :show, :create, :update, :destroy]
    end
  end
end

app/controllers/tenant_space_controller.rb
class TenantSpaceController < ApplicationController
  before_action :authenticate_tenant!
  def index

  #  @property_unit = PropertyUnit.find_by(tenant: current_tenant.id)
  #  @property = Property.find_by(id: @property_unit.property_id)
  #  @tenant = Tenant.find_by(id: current_tenant.id)
  #  @lease = Lease.find_by(tenant_id: current_tenant.id)

    puts "---- INFO FROM TENANT SPACE CONTROLLER"
    puts "-----"
    puts "current_tenant.id"
    p current_tenant.id
    puts "-"

  end

  def leases

    @tenant_lease = []

    Lease.find_each do |l|
      if l.tenant_id == current_tenant.id
        @tenant_lease.push(l)
      end
    end
     @tenant_lease.each do |l| p l.id end




  end
end

app/helpers/tenant_space_helper.rb
module TenantSpaceHelper
end

app/views/tenant_space/_menu.html.erb
<div class="tenant-icons-container">
<div class="row text-center">
<div class="col">
  <%= link_to tenant_space_path do %>
    <i class="fas fa-user"></i><br>
    <span class="tenant-icons-text">Opplysninger</span>
  <% end %>
</div>
<div class="col">
  <i class="fas fa-inbox"></i><br>
  Meldinger
</div>
<div class="col">
  <%= link_to tenant_space_leases_path do %>
    <i class="fas fa-file-contract"></i><br>
    Leiekontrakter
  <% end %>
</div>
<div class="col">
  <%= link_to edit_tenant_registration_path do %>
    <i class="fas fa-user-cog"></i><br>
    Innstillinger
  <% end %>
</div>
</div>
<hr class="divider">
</div>

app/views/tenant_space/index.html.erb
<div class="container ">
  <div class="tenant-container">
    <div class="row">
      <div class="col-md-12">
        <div class="tenant-headline">
          <h3><%= current_tenant.email %></h3>
        </div>
      </div>
    </div>
    <%= render 'menu' %>


      <div class="tenant-main-box">
        <div class="row ">
          <div class="col-md-6">
            <h4>Personopplysninger</h4>
            <ul class="list-group list-group-flush">
              <li class="list-group-item">
                Navn: <%= current_tenant.first_name %> <%= current_tenant.last_name %>
            </li>
            <li class="list-group-item">
                Epost: <%= current_tenant.email %>
            </li>
            <li class="list-group-item">
                Telefonnummer: <%= current_tenant.phone_number %>
            </li>
            <li class="list-group-item">
                Fødselsnummer: <%= current_tenant.phone_number %>
            </li>
            </ul>

          </div>
          <div class="col-md-6">
            <h4>Leieopplysninger</h4>
            <ul class="list-group list-group-flush">
            </ul>
          </div>
        </div>

      </div>

  </div>
</div>

app/views/tenant_space/leases.html.erb
<div class="container">
  <div class="tenant-container">
    <div class="row">
      <div class="col-md-12">
        <div class="tenant-headline">
          <h3><%= current_tenant.email %>
        </div>
      </div>
    </div>
    <%= render 'menu' %>
    <div class="tenant-main-box">
      <h4>Mine leiekontrakter</h4>
      <ul class="list-group list-group-flush">
        <% @tenant_lease.each do |enhet| %>
        <li class="list-group-item">
          <%= link_to "#{enhet.property_address},
                        Enhet #{enhet.unit_number}",
                        property_property_unit_lease_path(enhet.property_id,
                        enhet.property_unit_id, enhet.id), class: "tenant-leases-link" %>
        </li>
        <% end %>
      <ul>

    </div>
  </div>

</div>