config/routes.rb
Rails.application.routes.draw do
  resources :bug_reports, except: [:edit, :update]
  resources :documents
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :tenants
  resources :foobars

  #nesting property units under
  resources :properties do
    resources :property_units do
      resources :leases, only: [:new, :show, :create, :destroy]
      resources :documents, only: [:index, :new, :show, :create, :destroy]
    end
  end
  devise_for :users, path: "user", controllers: { sessions: "users/sessions", registrations: "users/registrations"}

  devise_for :tenants, path: "tenant_space", controllers: { sessions: "tenants/sessions", confirmations: "tenants/confirmations", registrations: "tenants/registrations"}
  get 'tenant_space/index', as: 'tenant_space'
  get 'tenant_space/leases'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "properties#index"


  # Todo API namespace, makes routes render at /api/v1/todo_items
  # defaults { format: :json } ensures that the data returned from the routes is JSON.
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :todo_items, only: [:index, :show, :create, :update, :destroy]
    end
  end
end

app/views/layouts/shared/_header.html.erb
<nav class="navbar  navbar-expand-md upper-navbar navbar-dark">
  <!-- <img class="navbar-brand" src="http://acmsocc.github.io/2016/assets/img/googlelogo_color_324x112dp.png" id="logo_custom" width="10%"  alt="logo"> -->
  <%= link_to "PropGrid", properties_path, class: "navbar-brand" %>



  <div class="container">
    <button class="navbar-toggler navbar-toggler-right custom-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
      <span class="navbar-toggler-icon "></span>
    </button>
    <div class="collapse navbar-collapse " id="collapsibleNavbar">
      <%= render 'layouts/shared/header_logins' %>
    </div>
  </div>
</nav>
<% if user_signed_in? %>
<nav class="navbar  navbar-expand-md lower-navbar ">
  <div class="container ">
    <button class="navbar-toggler navbar-toggler-right custom-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
      <span class="navbar-toggler-icon "></span>
    </button>
    <div class="collapse navbar-collapse d-flex justify-content-center" id="collapsibleNavbar">
      <ul class="navbar-nav m  ">


        <li class="nav-item mid-box">
          <b><%= link_to "Eiendom", properties_path, class: "mid-box-button" %></b>
        </li>
        <li class="nav-item mid-box">
          <b><%= link_to "Leietakere", tenants_path, class: "mid-box-button" %></b>
        </li>
        <li class="nav-item mid-box ">
          <a class="mid-box-button" href="#offer" disabled><b>Innboks</b></a>
        </li>
        <li class="nav-item">
        </li>

      </ul>


    </div>
  </div>
</nav>
  <% end %>

app/views/layouts/shared/_header_logins.html.erb
<ul class="navbar-nav ml-auto ">
  <li class="nav-item navbar-links">
    <% if user_signed_in? %>
      <% if current_user.admin_role? %>
      <%= link_to "Admin", rails_admin_path, class: "nav-link" %>
    <% end %>
    <% end %>
  </li>
    <% if user_signed_in? %>
  <li class="nav-item navbar-links">
    <%= link_to edit_user_registration_path, class: "nav-link" do %>
    <i class="fas fa-cog"></i>
    <% end %>
  </li>
  <li class="nav-item navbar-links">
      <%= link_to 'Logg ut', destroy_user_session_path, method: :delete, class: "nav-link" %>
    <% elsif current_tenant %>
      <%= link_to "Support", new_bug_report_path, class: "nav-link" %>
      <%= link_to 'Logg ut', destroy_tenant_session_path, method: :delete, class: "nav-link" %>
    <% else %>
  </li>
  <li>
    <div class="dropdown dropleft">
      <a  class="dropdown-toggle nav-link"
          id="dropdownLoginLink"
          data-toggle="dropdown"
          aria-haspopup="true"
          aria-expanded="false">
          Innlogging
      </a>
      <div class="dropdown-menu aria-labelledby="dropdownLoginLink">
      <%= link_to 'Huseier', new_user_session_path, class: "dropdown-item" %>
      <div class="dropdown-divider"></div>
      <%= link_to 'Leietaker', new_tenant_session_path, class: "dropdown-item" %>

      </div>
    </div>
  </li>
  <% end %>

</ul>

app/views/layouts/shared/_sidebar.html.erb
<div id="wrapper">
  <nav id="sidebar-wrapper">

    <ul class="sidebar-nav">
        <li class="sidebar-brand">
          PropGrid
        </li>
        <li>
          <span class="navi-info">NAVIGASJON</span>
        </li>
        <li>
          <%= link_to properties_path do %>
          <i class="fa fa-desktop"></i>
          Dashboard
          <% end %>
        </li>
        <li>
          <%= link_to "#" do %>
          <i class="fa fa-inbox"></i>
          Meldinger
          <% end %>
        </li>
        <hr class="divider">
        <li>
          <%= link_to properties_path do %>
          <i class="fa fa-home"></i>
          Eiendommer
          <% end %>
        </li>
        <li>
          <%= link_to tenants_path do %>
          <i class="fa fa-users"></i>
          Leietakere
          <% end %>
        </li>
        <hr class="sidebar-divider">
          <% if user_signed_in? %>
            <% if current_user.admin_role? %>
              <li>
                <%= link_to rails_admin_path do %>
                  <i class="fa fa-toolbox"></i>
                  Admin
                <% end %>
              </li>

              <li>
                <%= link_to bug_reports_path do %>
                  <i class="fa fa-bug"></i>
                  Brukerhenvendelser
                <% end %>
              </li>
            <% end %>
          <% end %>
          <% if current_user.admin_role? == false %>
        <li>
          <%= link_to new_bug_report_path do %>
            <i class="fa fa-bug"></i>
            Support
          <% end %>

        </li>
        <% end %>
        <li>
          <%= link_to  edit_user_registration_path do %>
          <i class="fa fa-cogs"></i>
          Innstillinger
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <span class="fa fa-sign-out"></span>
            Logg ut
          <% end %>
        </li>
      <!--  <hr class="sidebar-divider">
        <li class="active">

          <a href="#homeSubmenu" data-toggle="collapse"
                                aria-expanded="false"
                                class="dropdown-toggle">Home</a>
            <ul class="collapse list-unstyled" id="homeSubmenu">
              <li><a href="#">Home 1</a></li>
              <li><a href="#">Home 2</a></li>
              <li><a href="#">Home 3</a></li>

            </ul>
        </li>
        <li>
          <a href="#">Link 2</a>
        </li>
        <li>
          <a href="#">Link 3</a>
        </li> -->
    </ul>
  </nav>

app/views/layouts/shared/_topnav.html.erb
<div class="topline fixed-top">

</div>
<script>
   $("#menu-toggle").click(function(e) {
       e.preventDefault();
       $("#wrapper").toggleClass("toggled");
   });


   </script>
<a href="#menu-toggle" id="menu-toggle">Toggle Menu</a>