config/routes.rb
Rails.application.routes.draw do
  resources :bug_reports, except: [:edit, :update]
  resources :documents
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :tenants
  resources :foobars

  #nesting property units under
  resources :properties do
    resources :property_units do
      resources :leases, only: [:new, :show, :create, :destroy]
      resources :documents, only: [:index, :new, :show, :create, :destroy]
    end
  end
  devise_for :users, path: "user", controllers: { sessions: "users/sessions", registrations: "users/registrations"}

  devise_for :tenants, path: "tenant_space", controllers: { sessions: "tenants/sessions", confirmations: "tenants/confirmations", registrations: "tenants/registrations"}
  get 'tenant_space/index', as: 'tenant_space'
  get 'tenant_space/leases'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "properties#index"


  # Todo API namespace, makes routes render at /api/v1/todo_items
  # defaults { format: :json } ensures that the data returned from the routes is JSON.
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :todo_items, only: [:index, :show, :create, :update, :destroy]
    end
  end
end

app/models/foobar.rb
class Foobar < ApplicationRecord
end

app/controllers/foobars_controller.rb
class FoobarsController < ApplicationController
  before_action :set_foobar, only: [:show, :edit, :update, :destroy]

  # GET /foobars
  # GET /foobars.json
  def index
    @foobars = Foobar.all
  end

  # GET /foobars/1
  # GET /foobars/1.json
  def show
  end

  # GET /foobars/new
  def new
    @foobar = Foobar.new
  end

  # GET /foobars/1/edit
  def edit
  end

  # POST /foobars
  # POST /foobars.json
  def create
    @foobar = Foobar.new(foobar_params)

    respond_to do |format|
      if @foobar.save
        format.html { redirect_to @foobar, notice: 'Foobar was successfully created.' }
        format.json { render :show, status: :created, location: @foobar }
      else
        format.html { render :new }
        format.json { render json: @foobar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foobars/1
  # PATCH/PUT /foobars/1.json
  def update
    respond_to do |format|
      if @foobar.update(foobar_params)
        format.html { redirect_to @foobar, notice: 'Foobar was successfully updated.' }
        format.json { render :show, status: :ok, location: @foobar }
      else
        format.html { render :edit }
        format.json { render json: @foobar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foobars/1
  # DELETE /foobars/1.json
  def destroy
    @foobar.destroy
    respond_to do |format|
      format.html { redirect_to foobars_url, notice: 'Foobar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_foobar
      @foobar = Foobar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def foobar_params
      params.require(:foobar).permit(:name, :number)
    end
end

app/helpers/foobars_helper.rb
module FoobarsHelper
end

app/views/foobars/_form.html.erb
<%= form_with(model: foobar, local: true) do |form| %>
  <% if foobar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(foobar.errors.count, "error") %> prohibited this foobar from being saved:</h2>

      <ul>
        <% foobar.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :doc %>
    <%= form.file_field :doc, direct_upload: true %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/foobars/edit.html.erb
<h1>Editing Foobar</h1>

<%= render 'form', foobar: @foobar %>

<%= link_to 'Show', @foobar %> |
<%= link_to 'Back', foobars_path %>

app/views/foobars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Foobars</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @foobars.each do |foobar| %>
      <tr>
        <td><%= foobar.name %></td>
        <td><%= foobar.number %></td>
        <td><%= link_to 'Show', foobar %></td>
        <td><%= link_to 'Edit', edit_foobar_path(foobar) %></td>
        <td><%= link_to 'Destroy', foobar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Foobar', new_foobar_path %>

app/views/foobars/new.html.erb
<h1>New Foobar</h1>

<%= render 'form', foobar: @foobar %>

<%= link_to 'Back', foobars_path %>

app/views/foobars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @foobar.name %>
</p>

<p>
  <strong>Number:</strong>
  <%= @foobar.number %>
</p>

<%= link_to 'Edit', edit_foobar_path(@foobar) %> |
<%= link_to 'Back', foobars_path %>