config/routes.rb
Rails.application.routes.draw do
  resources :bug_reports, except: [:edit, :update]
  resources :documents
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :tenants
  resources :foobars

  #nesting property units under
  resources :properties do
    resources :property_units do
      resources :leases, only: [:new, :show, :create, :destroy]
      resources :documents, only: [:index, :new, :show, :create, :destroy]
    end
  end
  devise_for :users, path: "user", controllers: { sessions: "users/sessions", registrations: "users/registrations"}

  devise_for :tenants, path: "tenant_space", controllers: { sessions: "tenants/sessions", confirmations: "tenants/confirmations", registrations: "tenants/registrations"}
  get 'tenant_space/index', as: 'tenant_space'
  get 'tenant_space/leases'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "properties#index"


  # Todo API namespace, makes routes render at /api/v1/todo_items
  # defaults { format: :json } ensures that the data returned from the routes is JSON.
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :todo_items, only: [:index, :show, :create, :update, :destroy]
    end
  end
end

app/models/document.rb
class Document < ApplicationRecord
  has_one_attached :doc
  has_one :user
  has_one :property_unit
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_document, only: [:show, :edit, :update, :destroy]
    before_action :get_property_unit
    before_action :get_property
    before_action :proper_user

    require "image_processing/mini_magick"



    # GET /documents
    # GET /documents.json
    def index
    #  @documents = Document.all
      @document = Document.new
      @documents = @property_unit.documents
      # @documents = @property_units.documents


      puts "-------"
      puts "-------"


      @property_units = @property.property_units

      proper_user
      add_breadcrumb "Eiendommer", properties_path
      add_breadcrumb "Enheter ", @property
      add_breadcrumb "Enhet #{@property_unit.unit_number}", [@property, @property_unit]
      add_breadcrumb "Dokumenter", [@property, @property_unit, @document]

    end

    # GET /documents/1
    # GET /documents/1.json
    def show
    end

    # GET /documents/new
    def new
      @document = @property.property_unit.documents.build
      @document = Document.new

      @property_unit = @property.property_units.build
      proper_user
    end

    # GET /documents/1/edit
    def edit
    end

    # POST /documents
    # POST /documents.json
    def create
      user_id = current_user.id
      @document = Document.new(document_params)
      @document = @property_unit.documents.build(document_params.merge(user_id: user_id))
      #@property_unit = @property.property_units.build(property_unit_params.merge(user_id: current_user.id))

      uploaded_item = params[:document][:doc]
      file_type = uploaded_item.content_type
    # this should probably go in the model..
      if file_type.include?("image")
        mini_image = MiniMagick::Image.new(uploaded_item.tempfile.path)
        mini_image.resize '1200x1200'
      end
      respond_to do |format|
        if @document.save
          format.html { redirect_to property_property_unit_documents_path(@property, @property_unit), notice: 'Dokumentet ble lagret.' }
          format.json { render :show, status: :created, location: @document }
        else
          format.html { render :new }
          format.json { render json: @document.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /documents/1
    # PATCH/PUT /documents/1.json
    def update
      respond_to do |format|
        if @document.update(document_params)
          format.html { redirect_to @document, notice: 'Document was successfully updated.' }
          format.json { render :show, status: :ok, location: @document }
        else
          format.html { render :edit }
          format.json { render json: @document.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /documents/1
    # DELETE /documents/1.json
    def destroy
      puts "------------------------"
      document_item = ActiveStorage::Attachment.find(@document.doc.id)
      p document_item.purge
      puts "------------------------"

      @document.destroy
      respond_to do |format|




        format.html { redirect_to property_property_unit_documents_path(@property, @property_unit), notice: 'Dokumentet ble slettet.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_document
        @document = Document.find(params[:id])
      end

      def get_property
        @property = Property.find(params[:property_id])
      end

      def get_property_unit
        @property_unit = PropertyUnit.find(params[:property_unit_id])
      end

      def proper_user
        owner_id = @property_unit.user_id

        if current_user.id != owner_id
          redirect_to properties_url
          flash[:info ] = 'Fant ikke det du letet etter.'
        end
      end



      # Never trust parameters from the scary internet, only allow the white list through.

      def document_params
        params.require(:document).permit(:title, :doc)
      end
end

app/helpers/documents_helper.rb
module DocumentsHelper
  def document_icon(file_name)
    if file_name.to_s.upcase.include?('.PDF')
      raw('<i class="far fa-file-pdf document-list-icon"></i>')
    elsif file_name.to_s.upcase.include?('.DOC' || '.DOCX')
      raw('<i class="far fa-file-word document-list-icon"></i>')
    elsif file_name.to_s.upcase.include?('.PPT' || '.PPTX')
      raw('<i class="far fa-file-powerpoint document-list-icon"></i>')
    elsif file_name.to_s.upcase.include?('.XLS' || '.XLSX')
      raw('<i class="far fa-file-excel document-list-icon"></i>')
    elsif file_name.to_s.upcase.include?('PNG' || 'JPG' || 'JPEG' || 'BMP')
      raw('<i class="far fa-file-image document-list-icon"></i>')
    else
      raw('<i class="far fa-file document-list-icon"></i>')
    end
  end
end

app/views/documents/_form.html.erb
<%= form_with(model: [@property, @property_unit, document], local: true, html: {'class': "document-form"}) do |form| %>
  <% if document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
        <% document.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


        <div class="col-md-2">

            <%= form.submit "Last opp", class: "btn btn-primary-c btn-upload"%>
        </div>

      <div class="col-md-4">
        <%= form.text_field :title, placeholder: "Dokumentnavn", class: "form-control document-title-field" %>
      </div>

      <div class="col-md-4 " >

            <%= form.file_field :doc, class: "custom-file-input", id: "documentUpload", 'aria-describedby': "fileHelp" %>
            <%= form.label :doc, "Ingen fil er valgt", class: "custom-file-label", for: "documentUpload"  %>
      </div>


<% end %>

app/views/documents/_new.html.erb
<h1>Document</h1>

<%= render 'form', document: @document %>

<%= link_to 'Back', documents_path%>

app/views/documents/index.html.erb
<div class="container">
  <div class="breadcrumbs">
    <%= render_breadcrumbs %>
  </div>

  <div class="main-background main-container">

    <div class="row">
      <div class="col-md-12">
        <h4>Dokumenter</h4>
      </div>
    </div>

    <hr class="divider">
    <%= render 'form', document: @document %>




    <hr class="divider">
    <div class="row ">
      <div class="col-md-12">

        <table class="table table-borderless table-striped table-hover">
          <% @documents.each do |document| %>
            <tr>
              <td>
                <div class="document-list-cell">
                  <%= link_to rails_blob_path(document.doc), class: "document-link" do %>
                    <%= document_icon(document.doc.filename) %>
                    <%= document.title %> <span class="small">( <%= document.doc.filename %> )</span>
                  <% end %>
              </div>
            </td>
            <td><%= link_to "Slett", [@property, @property_unit, document],
                            method: :delete, data: {confirm: "Er du helt sikker?"},
                            class: "btn btn-danger" %></td>
          </tr>
          <% end %>
        </table>
      </div>
    </div>

  </div>
</div>
<script>
// Add the following code if you want the name of the file appear on select
$(".custom-file-input").on("change", function() {
  var fileName = $(this).val().split("\\").pop();
  $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
});


</script>

app/views/documents/new.html.erb
<h1>Document</h1>

<%= render 'form', document: @document %>

<%= link_to 'Back', documents_path%>

app/views/documents/show.html.erb
<p id'="notice"><%= notice %></p>
<br><br><br><br><br><br>

<p>
  <strong>Name:</strong>
  <%= @document.title %>
</p>

<p>
  <strong>Number:</strong>
</p>

<p>
  <%= image_tag url_for(@document.doc) %>
</p>

<p>
  <%= link_to @document.doc.filename, rails_blob_path(@document.doc, disposition: "attachment") %>
</p>

<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>